### PR TITLE
Add Campaign support

### PR DESCRIPTION
**Pull request by pastorhudson**
This adds Campaign Create, Read, Update, Destroy and Preview.

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Thank you @pastorhudson This looks really good. It sounds like form #8 this is working well already for you. I'm sure it'll open up interesting use-cases for others as well.

**Comment by mikeckennedy** [comment]
I merged this @pastorhudson and did a bit of clean up (see https://github.com/mikeckennedy/listmonk/commit/026a50af9101f1ed9b2263aaae396e48589c3a26 ). 

Can you look at one thing before we call this done? On line 1024 of `impl/__init__.py`, there is a type error:

"Expected type 'list[int]', got 'list[dict]' instead "

Once that gets sorted, I'll push it to PyPI.

**Comment by mikeckennedy** [comment]
Also, one enhancement that would be nice if it's easy for you. In the function `listmonk.create_campaign()` there is a parameter `template_id=5,  # Optional Defaults to 1`. This uses a default number.

But listmonk has the concept of a default template:

Screenshot 2024-11-10 at 7 46 15 AM

Do you think you could make it default to the one set via the UI like above?

**Comment by pastorhudson** [comment]
> I merged this @pastorhudson and did a bit of clean up (see [026a50a](https://github.com/mikeckennedy/listmonk/commit/026a50af9101f1ed9b2263aaae396e48589c3a26) ).
> 
> Can you look at one thing before we call this done? On line 1024 of `impl/__init__.py`, there is a type error:
> 
> "Expected type 'list[int]', got 'list[dict]' instead "
> 
> Once that gets sorted, I'll push it to PyPI.

I think this is because campaign.lists is a list of dictionaries `{"name": "some_list_name", "id": 3}` but the update endpoint wants a list of just the id integers. I thought I handled this on line [115 of models/__init__.py](https://github.com/mikeckennedy/listmonk/blob/f8affab1fb4cd8ef30a9ed2f28e2ab139e0e8007/listmonk/models/__init__.py#L115).

This code works without error for me:

```python
new_campaign = listmonk.create_campaign(
                                name='Some Test',
                                subject='You won't believe how much clickbait is in this email!!',
                                body="The body",
                                )

print(new_campaign)
new_campaign.name = 'BETTER TEST'
new_campaign.lists = [1,2]
listmonk.update_campaign(new_campaign)
```

Can you tell me how to make the type error happen? I'm probably just misunderstanding.

**Comment by mikeckennedy** [comment]
Hey @pastorhudson The problem is not a runtime problem. It is a typing system problem as in mypy or PyCharm. See this image with the warning here:

Screenshot 2024-11-11 at 6 55 12 PM

In `UpdateCampaignModel` you set lists to be `list[int]` but in the `Campaign` class, lists is a `list[dict]`.

**Pull request merged**
